# Generated by Django 4.1.13 on 2025-11-10 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('motion', 'Motion'), ('light', 'Light'), ('gas', 'Gas')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
