# Generated by Django 4.1.13 on 2025-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_iotdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='sensor_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
