# Generated by Django 5.2.7 on 2025-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_esp32data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esp32data',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='esp32data',
            name='light',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='esp32data',
            name='smoke',
            field=models.CharField(max_length=50),
        ),
    ]
